baseURL = "https://wilonweb.github.io/hugo-blowfish-starter/"
title = "Mon site Blowfish Starter"
theme = "ananke"
defaultContentLanguage = "fr"
languageCode = "fr"
enableRobotsTXT = true


[pagination]
  pagerSize = 10


[params]
  description = "Starter Hugo + Blowfish + GitHub Pages"
  dateFormat = "02 Jan 2006"

[menu]
  [[menu.main]]
    name = "Accueil"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "À propos"
    pageRef = "/about"
    weight = 20
