name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'main' si ta branche principale s'appelle 'main'

permissions:
  contents: write  # Autorise à pousser dans le repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}  # Utilise le Personal Access Token que tu as ajouté comme secret
          publish_dir: ./public
          publish_branch: gh-pages  # Cette ligne est ajoutée pour spécifier la branche de déploiement
          force_orphan: true
