name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou 'main' si ta branche par défaut est 'main'

permissions:
  contents: write  # Autoriser à pousser sur le repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_ORPHAN: true  # Forcer l'utilisation de la branche 'gh-pages' même en cas de conflits
